apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: <access_key_id from console>
  access_key_secret: <access_key_secret_from_console>
  bucketnames: loki-logging-<random id from console>
  endpoint: https://s3.openshift-storage.svc:443
