apiVersion: v1
kind: Secret
metadata:
  name: loki-s3
  namespace: netobserv
stringData:
  access_key_id: <access key from GUI>
  access_key_secret: <access key secret from GUI>
  bucketnames: netobserv-loki-<random UID from GUI>
  endpoint: https://s3.openshift-storage.svc:443
